server:
  port: 8081

spring:
  application:
    name: UserService

  datasource:
    url: jdbc:postgresql://${PG_ENDPOINT:localhost:5432}/${PG_DATABASE}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 100
      properties:
        enable:
          idempotence: true
      acks: all

backblaze:
  b2:
    endpoint: ${BACKBLAZE_ENDPOINT}
    region: ${BACKBLAZE_REGION}
    bucket-name: java-lab
    access-key: ${BACKBLAZE_ACCESS_KEY}
    application-key: ${BACKBLAZE_APP_KEY}

auth:
  jwt:
    secret: ${JWT_SECRET}
    lifetime: ${JWT_LIFETIME:7d}

  confirmation-code:
    lifetime: 15m

kafka:
  topic-names:
    user-registered: ${USER_CREATED_TOPIC}